version: '2'

networks:
  ptc_mysql:
    driver: bridge

services:
  mysqlsvr:
    container_name: mysql
    image: 'mysql5.7v1.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_DATABASE: propll
      MYSQL_USER: propll
      MYSQL_PASSWORD: 'admin123'
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/mysql:/var/lib/mysql-logs
      - /etc/my.cnf:/etc/my.cnf
    networks:
      - ptc_mysql
    restart: always
