filebeat:

filebeat.inputs:
  - type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

input {
    beats {
        port => 5044
    }
}

output.elasticsearch:
  hosts: ["172.25.0.2:9200"]
  username: "elastic"
  password: "123456"

output.logstash:
    hosts: ["logstash:5044"]

setup.kibana: 
  host: "172.25.0.4:5601"
