version: '2.0'

services:
  nginx:
    restart: always
    privileged: true
    container_name: nginx
    image: nginxv1.2:latest
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - /data/conf.d:/etc/nginx/conf.d
      - /data/log:/var/log/nginx
      - /data/html:/usr/share/nginx/html
    environment:
      - NGINX_HOST=proprol.com
      - NGINX_PORT=80
      - NGINX_PORT=443
