version: '2'

services:

  graylog-mongo:
    restart: always
    image: mongo:3.6.4
    container_name: mongo
    expose:
      - "27017"
    volumes:
      - ../data/mongodb:/data/db
    networks:
      graylog:
        ipv4_address: 172.24.0.2
    restart: always

  elasticsearch:
    restart: always
    image: elasticsearch:5.6.9
    container_name: elasticsearch
    volumes:
      - ../data/graylog-elasticsearch:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      graylog:
        ipv4_address: 172.24.0.3
    depends_on:
      - graylog-mongo
    restart: always

  graylog:
    restart: always
    image: graylog/graylog:2.4.5-2
    container_name: graylog
    volumes:
      - ./services/graylog/config:/usr/share/graylog/data/config
      - ../data/graylog:/usr/share/graylog/data/journal
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=gr8r3hbnvfs73b8wefhweufpokdnc
      # Username
      - GRAYLOG_ROOT_USERNAME=admin
      # Password: admin
      # echo -n yourpassword | shasum -a 256
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://graylog-elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://graylog-mongo/graylog
      - GRAYLOG_ROOT_TIMEZONE=Asia/Shanghai
      # Your IP
      - GRAYLOG_WEB_ENDPOINT_URI=http://10.1.23.62:9000/api
      - GRAYLOG_WEB_LISTEN_URI=http://0.0.0.0:9000/
      - GRAYLOG_REST_LISTEN_URI=http://0.0.0.0:9000/api
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      graylog:
        ipv4_address: 172.24.0.4
    depends_on:
      - graylog-mongo
      - elasticsearch
    restart: always

networks:
  graylog:
    driver: bridge
    ipam:
      config:
       - subnet: 172.24.0.0/24
