version: '2'
services:
  web:
    mem_limit: 512m
    image: nginx:1.10
    ports:
      - "80:80"
    volumes:
      - ../data/nginx:/var/log/nginx
    networks:
      - default
      - es1_default

networks:
  es1_default:
    external:
      name: es_d_default

